---
- hosts: es
  remote_user: root
  tasks:
    - name: ssh key
      authorized_key:
        user: root
        exclusive: true
        manage_dir: true
        key: '$(< /root/.ssh/id_rsa.pub)'
    - name: copy yum
      copy:
        src: elk.repo
        dest: /etc/yum.repos.d/elk.repo
        owner: root
        group: root
        mode: 0644
    - name: install java-1.8.0-openjdk,elasticsearch
      yum:
        name: java-1.8.0-openjdk,elasticsearch
        state: installed
    - name: copy elasticsearch
      template:
        src: elasticsearch.yml
        dest: /etc/elasticsearch/elasticsearch.yml
        owner: root
        group: root
        mode: 0644
      notify: reload elasticsearch
      tags: esconf
    - name: enable elasticsearch
      service:
        name: elasticsearch
        state: restarted
        enabled: yes
 handlers:
   - name: reload elasticsearch
     service:
       name: elasticsearch
       state: restarted
